default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 2305
  host: localhost
  port: 5432

development:
  <<: *default
  database: crud

test:
  <<: *default
  database: crud

production:
  <<: *default
  database: crud
